version: '3.4'

networks:
  k6grafana:

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - k6grafana
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=k6
  grafana:
    image: grafana/grafana:latest
    networks:
      - k6grafana
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./dashboards/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./dashboards/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  k6:
    image: loadimpact/k6:latest
    networks:
      - k6grafana
    ports:
      - '6565:6565'
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./src/configs:/src/configs/
      - ./src/data:/src/data/
      - ./src/scenarios:/src/scenarios/
      - ./src/services:/src/services/
      - ./src/utils:/src/utils/
